### ISSUE TITLE
error: C2039: 'amap' : is not a member of 'cosmosstruc'

### ISSUE THREAD

**Issue by spacemig** [hsfl/cosmos-core#14]
**[Original report](https://bitbucket.org/cosmos-project/core/issue/14) by Miguel Nunes (Bitbucket: [spacemig](https://bitbucket.org/spacemig), GitHub: [spacemig](https://github.com/spacemig)).**

----------------------------------------

When compiling COSMOS core with MSVC I get this error

jsonlib.cpp:7000: error: C2039: 'amap' : is not a member of 'cosmosstruc'

**Comment by jrlewis213** [comment]
No longer contain amap.  Resolved!
