### ISSUE TITLE
fix agent_001 and 002 communication order

### ISSUE THREAD

**Issue by spacemig** [hsfl/cosmos-core#42]
Observed behavior: when starting agent_001 first, agent_002 won't communicate with agent_001
Expected behavior: agent_001 and agent_002 should connect and exchange information regardless of which one starts first
System information: current 'dev' branch

**Comment by jrlewis213** [comment]
started a slack thread about this...

**Comment by jrlewis213** [comment]
Should be fixed as per https://app.slack.com/client/T01CN5X5F2M/C01CPLEN86S/thread/C01C6E6SACV-1602832363.015300
